/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CollaborationsRouteImport } from './routes/collaborations'
import { Route as CompetitionsRouteImport } from './routes/competitions'
import { Route as FoodOrderingRouteImport } from './routes/food-ordering'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PartnerShopsRouteImport } from './routes/partner-shops'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaborationsRoute = CollaborationsRouteImport.update({
  id: '/collaborations',
  path: '/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionsRoute = CompetitionsRouteImport.update({
  id: '/competitions',
  path: '/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodOrderingRoute = FoodOrderingRouteImport.update({
  id: '/food-ordering',
  path: '/food-ordering',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerShopsRoute = PartnerShopsRouteImport.update({
  id: '/partner-shops',
  path: '/partner-shops',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertising': typeof AdvertisingRoute
  '/auth': typeof AuthRoute
  '/collaborations': typeof CollaborationsRoute
  '/competitions': typeof CompetitionsRoute
  '/food-ordering': typeof FoodOrderingRoute
  '/gallery': typeof GalleryRoute
  '/partner-shops': typeof PartnerShopsRoute
  '/policies': typeof PoliciesRoute
  '/services': typeof ServicesRoute
  '/bookings': typeof AuthenticatedBookingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertising': typeof AdvertisingRoute
  '/auth': typeof AuthRoute
  '/collaborations': typeof CollaborationsRoute
  '/competitions': typeof CompetitionsRoute
  '/food-ordering': typeof FoodOrderingRoute
  '/gallery': typeof GalleryRoute
  '/partner-shops': typeof PartnerShopsRoute
  '/policies': typeof PoliciesRoute
  '/services': typeof ServicesRoute
  '/bookings': typeof AuthenticatedBookingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/advertising': typeof AdvertisingRoute
  '/auth': typeof AuthRoute
  '/collaborations': typeof CollaborationsRoute
  '/competitions': typeof CompetitionsRoute
  '/food-ordering': typeof FoodOrderingRoute
  '/gallery': typeof GalleryRoute
  '/partner-shops': typeof PartnerShopsRoute
  '/policies': typeof PoliciesRoute
  '/services': typeof ServicesRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertising'
    | '/auth'
    | '/collaborations'
    | '/competitions'
    | '/food-ordering'
    | '/gallery'
    | '/partner-shops'
    | '/policies'
    | '/services'
    | '/bookings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertising'
    | '/auth'
    | '/collaborations'
    | '/competitions'
    | '/food-ordering'
    | '/gallery'
    | '/partner-shops'
    | '/policies'
    | '/services'
    | '/bookings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/advertising'
    | '/auth'
    | '/collaborations'
    | '/competitions'
    | '/food-ordering'
    | '/gallery'
    | '/partner-shops'
    | '/policies'
    | '/services'
    | '/_authenticated/bookings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdvertisingRoute: typeof AdvertisingRoute
  AuthRoute: typeof AuthRoute
  CollaborationsRoute: typeof CollaborationsRoute
  CompetitionsRoute: typeof CompetitionsRoute
  FoodOrderingRoute: typeof FoodOrderingRoute
  GalleryRoute: typeof GalleryRoute
  PartnerShopsRoute: typeof PartnerShopsRoute
  PoliciesRoute: typeof PoliciesRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborations': {
      id: '/collaborations'
      path: '/collaborations'
      fullPath: '/collaborations'
      preLoaderRoute: typeof CollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitions': {
      id: '/competitions'
      path: '/competitions'
      fullPath: '/competitions'
      preLoaderRoute: typeof CompetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-ordering': {
      id: '/food-ordering'
      path: '/food-ordering'
      fullPath: '/food-ordering'
      preLoaderRoute: typeof FoodOrderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-shops': {
      id: '/partner-shops'
      path: '/partner-shops'
      fullPath: '/partner-shops'
      preLoaderRoute: typeof PartnerShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdvertisingRoute: AdvertisingRoute,
  AuthRoute: AuthRoute,
  CollaborationsRoute: CollaborationsRoute,
  CompetitionsRoute: CompetitionsRoute,
  FoodOrderingRoute: FoodOrderingRoute,
  GalleryRoute: GalleryRoute,
  PartnerShopsRoute: PartnerShopsRoute,
  PoliciesRoute: PoliciesRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
